#server:
#  port: 3002
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/userdb
#    username: userAdmin
#    password: adminpw
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        ddl-auto: create
##        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#  application:
#    name: USER-SERVICE
