server:
  port: 3002

spring:
  datasource:
    url: jdbc:mysql://172.30.197.157:3306/usersql
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  application:
    name: USER-SERVICE
